### ISSUE TITLE
About the output density map's resolution.

### ISSUE THREAD

**Issue by H-Hui2277** [dylran/DiffuseDenoiseCount#10]
Thanks for your great work, and I want to know about the output density map's resolution. 

Is the output density map's resolution the same as the input image? Or it gets lower resolution than the input image? 
This would influence the computational performance, and I'm interested of it.

**Comment by dylran** [comment]
Yes, we are producing the density maps at the image resolution.
Yes, the size affects the computational time and you can reduce the size of the image as long as the inteference between adjacent kernels is insignificant.
