### ISSUE TITLE
Why can't I import the guided_diffusion package?

### ISSUE THREAD

**Issue by RyanGarrr** [dylran/DiffuseDenoiseCount#11]
Traceback (most recent call last):
  File "/home/grad/DiffuseDenoiseCount/scripts/super_res_train.py", line 21, in <module>
    from guided_diffusion import dist_util, logger
ModuleNotFoundError: No module named 'guided_diffusion'

**Comment by dylran** [comment]
Please make sure to have guided_diffusion folder in your current working directory. I have seen this issue in other code bases when the folder I need to import is not in the current working directory. Hope this will help.
