### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by chxnkm** [dylran/DiffuseDenoiseCount#12]
Hi repo authors! Looking to replicate the brilliant work done here, however, running the training script gave me this error. Is there anything I should look into first, or check on my side? Thank you!

**Comment by dylran** [comment]
Hi, could you provide more information on this?

**Comment by chxnkm** [comment]
Hello, thanks for the reply. Have since solved this issue due to a small error on the training script on my part. 👍🏻

**Comment by sainny** [comment]
> Hello, thanks for the reply. Have since solved this issue due to a small error on the training script on my part. 👍🏻
May I ask how you solved it? I also encountered the same issu
