### ISSUE TITLE
How is evaluation done exactly?

### ISSUE THREAD

**Issue by massarfusion** [dylran/DiffuseDenoiseCount#13]
Thanks again for this work, this really inspires me a lot. However there are 2 issues still bothering me that I cannot resolve myself:
1. When I try to remove auxiliary head from training(by multiplying corresponding loss value with zero), nonnegligible performance gain is witnessed (SHHA,200000 iterations ,MAE dropped from 1710 to 94, tested with super_res_sample.py). 
2. How evaluation results from paper([arxiv](https://arxiv.org/abs/2303.12790)) are calculated? Are MAE and MSE calculated on each patch then averaged later? In this case, how are overlapping areas handled? 
Thank you for your time reading through this.

**Comment by dylran** [comment]
We have modified the model and evaluation of the existing method. The updated codebase will be published when I have free time.

**Comment by 1286710929** [comment]
> Thanks again for this work, this really inspires me a lot. However there are 2 issues still bothering me that I cannot resolve myself:
> 
> 1. When I try to remove auxiliary head from training(by multiplying corresponding loss value with zero), nonnegligible performance gain is witnessed (SHHA,200000 iterations ,MAE dropped from 1710 to 94, tested with super_res_sample.py).
> 2. How evaluation results from paper([arxiv](https://arxiv.org/abs/2303.12790)) are calculated? Are MAE and MSE calculated on each patch then averaged later? In this case, how are overlapping areas handled?
>    Thank you for your time reading through this.

Hello, do you successfully reproduce this work? I encountered some problems during training. Can I ask you for the training code you reproduced?

**Comment by chxnkm** [comment]
Would also like to understand the code used to reproduce since I also encountered some problems in the training and testing procedures.
