### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by jin1041** [dylran/DiffuseDenoiseCount#15]
Thanks for your works , I find some errors in requiresments.txt, it shows like this:
```python
sentry-sdk @ file:///home/conda/feedstock_root/build_artifacts/sentry-sdk_1674487741133/work
setproctitle @ file:///home/conda/feedstock_root/build_artifacts/setproctitle_1649637304940/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1611376390914/work
```
maybe `pip list --format=freeze > requirements.txt` works.

**Comment by dylran** [comment]
Thank you! for the suggestion. Anyway, we have improved the method for better inference speed and performance. I will update the clean codebase when I have free time.
