### ISSUE TITLE
An issue of mismatched  pre-trained weights during import

### ISSUE THREAD

**Issue by SG12QT** [dylran/DiffuseDenoiseCount#3]
Firstly, thank you for your work which has greatly inspired my research. I encountered the following issue while attempting to run the testing script：
> RuntimeError: Error(s) in loading state_dict for SuperResModel:
	Missing key(s) in state_dict: "count_feat_normalization.weight", "count_feat_normalization.bias", "count_decoder.0.weight", "count_decoder.0.bias", "count_decoder.2.weight", "count_decoder.2.bias".

**Comment by kodonnell** [comment]
I'm getting the same error - any suggestions @dylran ?

**Comment by dylran** [comment]
Thank you for bringing this to our attention. We will fix this issue as soon as possible. In the meantime, you can change the [line 64](https://github.com/dylran/DiffuseDenoiseCount/blob/main/scripts/super_res_sample.py) as follows.
```python
model.load_state_dict(
        dist_util.load_state_dict(args.model_path, map_location="cpu"), strict=False) 
```
