### ISSUE TITLE
Program stopped by "assert false" when testing

### ISSUE THREAD

**Issue by massarfusion** [dylran/DiffuseDenoiseCount#6]
First of all, thank you for this amazing project.
There is a line of code in line 539 of ./gaussian_diffusion/gaussian_diffusion.py that keeps terminating the whole program.
[Here](https://github.com/dylran/DiffuseDenoiseCount/blob/5a0f6687ef4383af78cb21c2656d486c50383cd2/guided_diffusion/gaussian_diffusion.py#L539)
Is this line placed here by design? I only could see some new .mat files produced in the ./experiments folder, then this script is stopped. 
What should I do if I want to run through all instances in test data folder and see test results?

**Comment by makangzhe** [comment]
I have the same problem, have you solve this ?

**Comment by dylran** [comment]
Thank you for pointing this out. You can try removing the assertion. Anyway, the current code includes sections we used for the ablations. I will clean them in near future.
