### ISSUE TITLE
Where is the ”contour detection“ in code？

### ISSUE THREAD

**Issue by goodl-dayup** [dylran/DiffuseDenoiseCount#7]
Firstly, thank you for your work which has greatly inspired my research. 
In Introduction, it said "We introduce counting via contour detection made possible by the use of narrow kernels...".
In line 127 of "images_datasets.py", you use "count = np.sum(csv_density)" after the narrow Gaussian kernel processing. I'm confused where the contour detection code is. Can you help me point it out？

`csv_density = np.asarray(pd.read_csv(path,  header=None).values)`
` count =  np.sum(csv_density)`
` count = np.ceil(count) if count > 1 else count`

**Comment by dylran** [comment]
We didn't include the contour detection in the code base, however we have resorted to performing local maxima detection in the current version.
